config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  devise_for :users
  root to: 'pages#home'


mount Attachinary::Engine => " /attachinary "


  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/qui' => 'pages#qui'
  get '/mon_fonctionnement' => 'pages#mon_fonctionnement'
  get '/demarrer' => 'lessons#demarrer_un_projet_rails'
  get '/production' => 'lessons#production'
  get '/creer_des_branches' => 'lessons#creer_des_branches'
  get '/cloner_repo' => 'lessons#cloner_repo'
  get '/navbar_footer' => 'lessons#navbar_footer'
  get '/creer_formulaire' => 'lessons#creer_formulaire'
  get '/premieres_pages' => 'lessons#premieres_pages'
  get '/layout' => 'lessons#layout'
  get '/background_medias' => 'lessons#background_medias'
  get '/font_awesome' => 'lessons#font_awesome'
  get '/clefs_figaro' => 'lessons#clefs_figaro'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_attachments :photos, maximum: 8
    mount_uploader :photo, PhotoUploader


    geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/message.rb
class Message
  include ActiveModel::Model
attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: %i[show index]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    @markers = @lessons.map do |lesson|
      {
        lat: lesson.latitude,
        lng: lesson.longitude#,
      #   infoWindow: { content: render_to_string(partial: "/lessons/map_box", locals: { lesson: lesson }) }
    }
  end
end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
 end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }

      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }



      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:name, :description, :size, :sleep, :rooms, :bathroom, :minimum_stay, :address, :minimum_price, :maximum_person, :deposit_garantee, :cleaning, :parking_area, :swiming_pool, :air_conditioning, :internet_acces, :smoking, :homeaway_link, :golf, :spring, :summer, :fall, :winter, photos: [ ])
    end
  end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new message_params

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to new_message_url, notice: "Message received, thanks!"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :qui, :mon_fonctionnement]

  def home
    @lessons = Lesson.limit(3)
  end

  def qui
  end

  def mon_fonctionnement
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
     <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyBEdAEO0n6HjCISf4HMbSS6pd7oF-KKssY" %>
      <%= javascript_pack_tag "map" %>

  </body>
</html>

app/views/lessons/_form.html.erb
<div class='container'>
  <%= simple_form_for(@lesson) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.label :golf %>
    <%= f.select :golf, ["Golf des Vigiers", "Golf de Saint-Emilion", "Golf de Cameyrac", "Golf de Marmandes", "Golf du Medoc", "Golf Bordelais"], prompt: "A sélectionner..." %><br>
    <%= f.label :superficie %>
    <%= f.number_field :size  %><br>
    <%= f.label :description %>
    <%= f.text_area :description, rows:4, cols:125, placeholder: "Description ici" %><br>
    <%= f.label :chambres %>
    <%= f.number_field :rooms %><br>
    <%= f.label :couchage %>
    <%= f.number_field :sleep %><br>
    <%= f.label :salle_de_bain %>
    <%= f.number_field :bathroom %><br>
    <%= f.label :prix_de_depart %>
    <%= f.number_field :minimum_price %><br>
    <%= f.label :durée_minimale %>
    <%= f.number_field :minimum_stay %><br>
    <%= f.label :personnes_maximum %>
    <%= f.number_field :maximum_person %><br>
    <%= f.label :depot_garantie %>
    <%= f.number_field :deposit_garantee %><br>
    <%= f.label :frais_nettoyage %>
    <%= f.number_field :cleaning %><br>
    <%= f.label :parking %>
    <%= f.select :parking_area, ["yes outside", "yes inside", "no"], prompt: "Select..." %><br>
    <%= f.label :piscine %>
    <%= f.select :swiming_pool, ["yes", "no"], prompt: "Select..." %><br>
    <%= f.label :air_conditionne %>
    <%= f.select :air_conditioning, ["yes", "no"], prompt: "Select..." %><br>
    <%= f.label :acces_internet %>
    <%= f.select :internet_acces, ["yes", "no"], prompt: "Select..." %><br>
    <%= f.label :fumeur %>
    <%= f.select :smoking, ["accepted", "not accepted"], prompt: "Select..." %><br>
    <%= f.label :lien_annonce_abritel %>
    <%= f.text_field :homeaway_link, placeholder: "wwww.xxx.heroku-app.com", class: "form-control" %><br>
    <%= f.label :tarif_printemps %>
    <%= f.number_field :spring %><br>
    <%= f.label :tarif_ete %>
    <%= f.number_field :summer %><br>
    <%= f.label :tarif_automne %>
    <%= f.number_field :fall %><br>
    <%= f.label :tarif_hiver %>
    <%= f.number_field :winter %><br>

    Photo 1  <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %><br>
    Photo 2  <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %><br>

    <hr>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  <% end %>
</div>

app/views/lessons/_map_box.html.erb
<div class="info-window">
  <%= lesson.name %>
</div>

app/views/lessons/background_medias.html.erb
Un ensemble d’images Free sont disponibles sur:
https://unsplash.com/?ref=thestocks.im
Si l’on souhaite une image statique:
/* app/assets/stylesheets/components/_banner.scss */
.home-banner {
  background-image: asset-url(‘image.jpg’);
  background-size: cover;
  height: 100vh;
  color: #eee;
  text-align: center;
  padding-top: 40vh;
}
Et on appelle le component CSS:
/* app/assets/stylesheets/components/_index.scss */
@import "banner";

Si l’on souhaite une image avec scroll:
On crée un component CSS:
//background image home
.jumbotron {
  background-image: url('background2.jpg');
  background-size: cover;
  background-position: center;
  background-attachment: fixed;
  min-height: 70vh;
  color: #374344;
}
section {
  padding-top: 4rem;
}
Et on appelle la classe ou la section dans le html.

app/views/lessons/cloner_repo.html.erb
<div class="container">
  <h3>2. Cloner son repo Github</h3>
  <div class="col-xs-12 col-md-8">
    https://stackoverflow.com/questions/10963878/how-do-you-fork-your-own-repository-on-github
    Puis:
    https://services.github.com/on-demand/github-cli/clone-repo-cli
    Puis le deploy sur heroku
    Ne pas oublier le db:migrate, de changer les API sur heroku et en local, et dans confi/environment/production et saisir l’url heroku dans:
    config.action_mailer.default_url_options = { host: "XXXXXXX" }
    <div class="col-xs-12 col-md-4">
    </div>
  </div>
</div>

app/views/lessons/creer_des_branches.html.erb
<div class="container">
  <h3>2. Mettre un projet rails en production sur Heroku</h3>
  <div class="col-xs-12 col-md-8">
    On commence désormais les features de notre projet  à partir de nouvelles branches.
    Dés que l’on travaille sur une nouvelle feature, le mieux est de créer une nouvelle branche:
    > git checkout -b nom-de-la-branche : pour préer une branche à partir du master:
    Puis on enregistre au fur et à mesure notre travail lorsqu’une feature est terminée:
    > git status
    > git add .
    > git commit -m ‘descriptif de la modif’
    > git push origin nom-de-la-branche
    On va sur Github/ code:
    On valide le commit
    On merge le commit
    On revient sur la console pour revenir sur un projet propre qui a enregistré notre dernière feature avec:
    > git checkout master
    > git pull origin master
    On pousse sur heroku:
    > git push heroku master
    S’il y a eu une migration au cours de notre commit:
    > heroku run rake db:migrate
    On re-créer une nouvelle branche….et ainsi de suite
    <div class="col-xs-12 col-md-4">
    </div>
  </div>
</div>

app/views/lessons/creer_formulaire.html.erb
<div class="container">
  <h3>Creer un formulaire</h3>
  <div class="col-xs-12 col-md-5">
En simple_form, il n’y a qu’un type de balise: input qui reconnaît automatiquement l’attribut alors qu’en form_for on doit specifier:(text_field…number_field… et il n’y a pas besoin de label avec simple_form. Enfin Simple_form met automatiquement les classes bootstrap à notre place ( (form-group..form-control). Pour celà il faut que la gem simple_form soit installée et la config set-up de la gem installée.  exemple si on souhaite améliorer le simple_form:
 <h4>Ajouter une checkbox dans le formulaire avec multi-citères</h4>
 exmple pour créer des tags

https://rubyplus.com/articles/3191-Has-Many-Through-Checkboxes-in-Rails-3-x-4-x-and-5
 il faut aussi créer le modèle en question et lui faire un scaffol pour pouvoir créer les catégories.

  </div>
 <div class="col-xs-12 col-md-7">
  </div>
  </div>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
 <section class="background">
  <div class="container">
    <div class="panel panel-default box-shadow">
      <div class="panel-body">
        <div class="row">
          <div id="hidden-desktop">
           <h3><%= @lesson.name %> </h3>
           <h4><%= @lesson.golf %> <%= image_tag "vigiers.png", width: 50 %>
           </h4>
           <h5>starting from: <strong><%= @lesson.minimum_price %> eur/night</strong></h5>

         </div>

         <div class="col-md-6">
          <div id="my_carousel" class="carousel slide" data-ride="carousel">
            <!-- Bulles -->
            <ol class="carousel-indicators">
              <li data-target="#my_carousel" data-slide-to="0" class="active"></li>
              <li data-target="#my_carousel" data-slide-to="1"></li>
              <li data-target="#my_carousel" data-slide-to="2"></li>
            </ol>
            <!-- Slides -->
            <div class="carousel-inner">
              <!-- Page 1 -->
              <div class="item active">
                <div class="carousel-page">
                <%= cl_image_tag @lesson.photos.first.path, width: 400, height: 200, crop: :fill %>
                </div>
                <div class="carousel-caption">Séjour</div>
              </div>
              <!-- Page 2 -->
              <div class="item">
                <div class="carousel-page">

                 <%= cl_image_tag @lesson.photos.first.path, width: 400, height: 200, crop: :fill %></div>
                 <div class="carousel-caption">Chambre</div>
               </div>
               <!-- Page 3 -->
               <div class="item">
                <div class="carousel-page">
                 <%= cl_image_tag @lesson.photos.first.path, width: 400, height: 200, crop: :fill %>
               </div>
               <div class="carousel-caption">Salle de bain</div>
             </div>
           </div>
           <!-- Contrôles -->
           <a class="left carousel-control" href="#my_carousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
          </a>
          <a class="right carousel-control" href="#my_carousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>

        </div>
        <table style="width:80%">

          <tr>
            <th><h6><strong>Periods:</strong></h6></th>
            <th><h6><strong>Prices:</strong></h6></th>
          </tr>

          <tr>
            <td><h6>2018 Spring Prices</h6></td>
            <td><h6><strong><%= @lesson.spring %> eur/night</strong></h6></td>
          </tr>
          <tr>
            <td><h6>2018 Summer Prices</h6></td>
            <td><h6><strong><%= @lesson.summer %> eur/night</strong></h6></td>
          </tr>
          <tr>
            <td><h6>2018 Fall Prices</h6></td>
            <td><h6><strong><%= @lesson.fall %> eur/night</strong></h6></td>
          </tr>
          <tr>
            <td><h6>2018 Winter Prices</h6></td>
            <td><h6><strong><%= @lesson.winter %> eur/night</strong></h6></td>
          </tr>
        </table>
        <h6><strong>(minimum stay: <%= @lesson.minimum_stay %> nights)</strong></h6>
        <hr>
        <div class='text-center'>
          <h6><strong>Prices not including:</strong><br>
            - Cleaning: <strong><%= @lesson.cleaning %> eur per stay.</strong><br>
            - Stay taxes: 1eur/night/pers
            <br>
            <strong>Deposit Garantee: <%= @lesson.deposit_garantee %></strong>
          </h6>
        </div>

      </div>
      <div class="col-md-6">
        <div id="hidden-mobile">
         <h3><%= @lesson.name %> <%= image_tag "vigiers.png", class:"card-user-large" %>
         </h3>
         <h4><%= @lesson.golf %>
         </h4>
         <h5>starting from: <strong><%= @lesson.minimum_price %> eur/night</strong></h5>
       </div>
       <hr>
       <div class="row">
        <h5><%= @lesson.description %></h5>
        <div class="col-md-6 text-left">
          <ul>
            <li><h6>Rooms: <strong><%= @lesson.rooms %></strong></h6></li>
            <li><h6>Bathroom: <strong><%= @lesson.bathroom %></strong></h6></li>
            <li><h6>Max number of pers.: <strong><%= @lesson.maximum_person %></strong></h6></li>
            <li><h6>Parking area: <strong><%= @lesson.parking_area %></strong></h6></li>
          </ul>
        </div>
        <div class="col-md-6 text-left">
          <ul>
            <li><h6>Swiming Pool: <strong><%= @lesson.swiming_pool %></strong></h6></li>
            <li><h6>Air Conditioning: <strong><%= @lesson.air_conditioning %></strong></h6></li>
            <li><h6>Internet acces by wifi: <strong><%= @lesson.internet_acces %></strong></h6></li>
            <li><h6>Smoking: <strong><%= @lesson.smoking %></strong></h6></li>
          </ul>
        </div>
      </div>
      <hr>
      <div class="text-center">
        <h5><%= link_to 'Need more information', new_message_path, class:'btn btn-info' %> <br><br> <%= link_to "#{@lesson.homeaway_link}", class:'btn btn-info', target: :_blank do %>  Book online with: <%= image_tag "abritel.png", width: 60 %><% end %></h5>

      </div>
    </div>
  </div>
</div>
</div>
<div class='text-center'>
  <h5> <%= link_to 'Back to Properties', lessons_path %> </h5>
</div>
</div>
</section>

app/views/messages/new.html.erb
 <section class="background">
  <div class="container">
    <div class='row'>
      <div class='col-xs-3'></div>
      <div class='col-xs-6'>
        <div class="box-shadow">
          <br>
          <h4>Contact-us for more information about your stay</h4>
          <%= form_for @message, url: create_message_url do |f| %>
          <%= notice %>
          <%= @message.errors.full_messages.join(', ') %><br><br>
          Name:
          <%= f.text_field :name, placeholder: 'name' %>
          Email:
          <%= f.email_field :email, placeholder: 'email' %><br><br>
          Message:
          <%= f.text_area :body, placeholder: 'body' %><br><br>
          <%= f.submit 'Send' %>
          <% end %>
        </div>
      </div>
      <div class='col-xs-3'></div>
    </div>
  </div>
</section>

app/views/pages/home.html.erb
<section class="background">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-1"></div>
      <div class="col-xs-12 col-md-5">
        <h2><strong>Golf Rental Properties</strong></h2>
        <h4><strong>Find your next golf course accomodation</strong></h4>
        <p>Discover the best places for your golf stay </p>
        <%= image_tag "vigiers.png", width:60 %> <%= image_tag "westin.png", width:60 %> <%= image_tag "logo_royan.png", width:60 %>
      </div>
      <div class="col-xs-12 col-md-3"></div>
      <div class=" col-xs-12 col-md-3">
        <div id="hidden-mobile">
          <div class="box-shadow">
           <section>
            <h5 style="color:white;"><%= image_tag "phone.png", width: 35 %> <strong>Contact us </strong></h5>
            <h5>(+33) (0)6 81 503710 <br>
              join@golfrental.com</h5>
              <hr>
              <strong> <%= link_to  mon_fonctionnement_path do %>
                <%= image_tag "white_house.png", heigth:35, width: 25 %>  Plan to rent your house</strong>
                <% end %>
                <br><br>
              </strong>
            </div>
          </div>
        </div>
      </div>
      <div class="row text-center" >
       <div id="hidden-desktop">`<br><br><br><br><br><br><br>
        <%= link_to "Discover all our properties", lessons_path, class:'btn btn-primary' %>
      </div>
      <div class="col-xs-12 arrow">
        <div id="hidden-mobile">
          <%= link_to "/#creators" do %>
          <h5><strong>Discover our last properties</strong><h5><br>
            <%= image_tag "arrow_down.png", width: 45 %>
            <% end %>
          </div>
        </h5>
      </div>
    </section>
    <br>
    <div class="container">
      <div id='creators'>
        <div class="row">
          <div class='col-xs-12'>
            <% @lessons.each do |lesson| %>
 <div class="col-xs-12 col-sm-4">
            <%= link_to lesson do %>


            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1465670277367-f9c604766898?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=844e76eabeeb23c17ce07467ea424061&auto=format&fit=crop&w=1738&q=80');">


            <div class="card-category"><%= lesson.golf%></div>
            <div class="card-description">
              <h2><%= lesson.name %></h2>
              <p>from <%= lesson.minimum_price %> eur</p>
            </div>
            <%= image_tag "vigiers.png", class:"card-user" %>
            <div class="card-link">
            </div>
          </div>
          <br>
          <% end %>
          </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>
  <hr>

<!--
        <div class='text-center'>
          <h4><strong>Fantastic properties located on the golf course</strong></h4><br>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1465670277367-f9c604766898?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=844e76eabeeb23c17ce07467ea424061&auto=format&fit=crop&w=1738&q=80');">
              <div class="card-category">Chateau des Vigiers</div>
              <div class="card-description">
                <h2>Sweet Condo 4 pers</h2>
                <p>from 90eur/night</p>
              </div>
              <%= image_tag "vigiers.png", class:"card-user" %>
              <a class="card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1522362299427-cf74c685a60c?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a24de15e02e769f7a71ce5c1ad80804b&auto=format&fit=crop&w=1500&q=80');">
              <div class="card-category">Golf de Royan</div>
              <div class="card-description">
                <h2>Nice Villa 6 pers</h2>
                <p>from 120eur/night</p>
              </div>
              <%= image_tag "westin.png", class:"card-user" %>
              <a class="card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
           <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1503525635880-11dd8ee741a4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ea1e92650d20f00f19ea4ead55df2c70&auto=format&fit=crop&w=1762&q=80');">
            <div class="card-category">Golf de Biscarosse</div>
            <div class="card-description">
              <h2>Nice Villa 6 pers</h2>
              <p>from 100eur/night</p>
            </div>
            <%= image_tag "westin.png", class:"card-user" %>
            <a class="card-link" href="#" ></a>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-xs-12 text-right">
          <%= link_to "Discover all our properties", lessons_path %>
        </div>
      </div>
      <hr>
    </div>
  </div>
-->
<div class="container">
  <div class="row" >
   <div class="col-xs-4 text-center">
     <%= image_tag "house.png", width:80 %><br>
     Get the best accomadation and location places to discover surrounding as well
   </div>
   <div class="col-xs-4 text-center">
     <%= image_tag "club_car.png", width:80 %><br>
     Access to golf and accomodation services from your place
   </div>
   <div class="col-xs-4 text-center">
    <%= image_tag "course.png", width:80 %><br>
    Easiest way to participate to the golf competiton with no stress.<br> <%= link_to 'Have a look at our Golf Courses Partners', mon_fonctionnement_path %>
  </div>


</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Enjoy your golf parties with fantastic accomodations
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo_golf.png", height: 50 %> <strong>Golf Rental Properties</strong>
  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
   <%= link_to "Our properties", lessons_path, class: "navbar-wagon-item navbar-wagon-link"  %>

   <%= link_to "Golf courses Partnership", qui_path, class: "navbar-wagon-item navbar-wagon-link"  %>
   <% if user_signed_in? %>

   <!-- Links when logged in -->

   <%= link_to "Ajouter une propriété", new_lesson_path, class: "navbar-wagon-item navbar-wagon-link"  %>

   <!-- Avatar with dropdown menu -->
   <div class="navbar-wagon-item">
    <div class="dropdown">
       <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
      <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "#" do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
          <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <% else %>
  <!-- Login link (when logged out) -->
  <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <% end %>
</div>

<!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li><a href="#">Some mobile link</a></li>
      <li><a href="#">Other one</a></li>
      <li><a href="#">Other one</a></li>
    </ul>
  </div>
</div>
</div>